import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/globals.css";

import { headers } from 'next/headers'

import { config } from '@/wagmi.config';
import { Providers } from "@/app/lib/providers/providers";
import { cookieToInitialState } from 'wagmi'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));
  return (
    <html lang="en">
        <body className={inter.className}>
          <Providers initialState={initialState}>
            {children}
          </Providers>
        </body>
    </html>
  );
}
